### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by yopop666** [scaytrase/symfony-switchable-theme#4]
Hi ,
I installed this bundle, but I don't know how to make it to work.
Please give me a sample of code.
Regards,
Andrei!

**Comment by scaytrase** [comment]
Good point. I'll try to update readme soon and implement some demonstrating tests.

Shortly you should just create a service-class implementing `ThemeInterface` which methods provide you with template paths and put them to the registry (manually via DI or via `{ name: theme }` tag). Implementing several themes allows you to choose them at runtime.

Example of usage is simple

``` php
class MyTheme implements ThemeInterface {
    public function get($layout = 'base') {return 'MyBundle:MyTheme:base.html.twig';}
    public function all() {return array('base' => 'MyBundle:MyTheme:base.html.twig');}
    public function getType() {return 'my_theme';}
}
```

``` twig
{# MyBundle:MyTheme:base.html.twig #}
Here your theme basic template goes.
```

``` twig
{# YourBundle::base.twig.html #}
{% extends theme_registry.template('my_theme','base') %}
```

The main idea is that 'my_theme' and 'base' strings could be variables, which you fetch from the database or user session.

I've merged latest changes to the master, they should be more consistent.

For advanced usage I've implemented an abstract BootstrapThemes which could be extended to compile several different `bootstrap.css` files for different themes to use them.
